### ISSUE TITLE
List of results

### ISSUE THREAD

**Issue by TKSJ2020** [FGPLab/cydrasil#11]
Hello,

I am analysing 16S rRNA amplicon sequencing data and I would like to assign better the OTU classified as cyanobacteria I find my samples. I think cyadrasil does a better job than other current databases, but I was wondering if it is possible to get the results in a table format (.csv for example), so I could see my samples and the distances to each reference strain. Something similar to what we can see in the iTOL, but in one single table (or multiple table per sample). 

Thank you in advance for any advice!

Best regards

**Comment by droush** [comment]
Hello!

As of right now, we do not have an implementation to do this. The JPLACE output file from EPA-ng may have this data, and you could theoretically write a script to extract it to a csv format (or there may be one available in pplacer tools). 

We didn't write this implementation because we want users to physically see where each OTU/ASV lands in a phylogenetic context, instead of just going off of a name giving through a classification.
